//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int ID { get; set; }
        public string Name_Client { get; set; }
        public Nullable<int> NumberPassport { get; set; }
        public Nullable<int> id_Brand { get; set; }
        public string model { get; set; }
        public string year { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public string Techical_Condition { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Status Status { get; set; }
    }
}
